package com.opendev.bolao.taglib;

import java.io.IOException;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.jsp.JspException;
import jakarta.servlet.jsp.JspWriter;
import jakarta.servlet.jsp.tagext.BodyTagSupport;

public class PortletTag extends BodyTagSupport {

	
	private static final long serialVersionUID = 1L;
	
	private String icon;
	private String title;
	private String contentUrl;
	private String autorefreshRate;
	private String style;
	
	private StringBuffer html;
	
	public int doStartTag() throws JspException {
		HttpServletRequest request = (HttpServletRequest) pageContext.getRequest();
		html = new StringBuffer();
		html.append("<!-- Portlet generated by opendev:portlet tag. ID = " + getId() + " -->");
		if (getContentUrl() != null) {
			this.contentUrl = request.getContextPath() + getContentUrl();
			html.append("\n<script type=\"text/javascript\" >");
			html.append("\n\taddOnLoadEvent(function () {update_" + getId() + "(\"" + this.contentUrl + "\", " + getAutorefreshRate() + "); });");
			html.append("\n</script>");
		}
		html.append("\n<div");
		html.append(" id=\"");
		html.append(getId());
		html.append("\" class=\"");
		html.append("portlet\"");
		if (getStyle() != null && getStyle().trim().length() > 0) {
			html.append(" style=\""+ getStyle() +"\"");
		}
		html.append(">\n");
//		html.append("\t<div class=\"controls\">");
//		html.append("</div>");
		html.append("\n\t<div class=\"title\">");
		html.append("\n\t\t<span>");
		if (getIcon() != null && getIcon().length() > 0) {
			html.append("<img alt=\"");
			html.append(getTitle());
			html.append("\" src=\"");
			html.append(((HttpServletRequest)pageContext.getRequest()).getContextPath());
			html.append(getIcon());
			html.append("\" style=\"vertical-align: middle;\" />");
		}
		html.append("</span>");
		html.append("\n\t\t<span>");
		html.append(getTitle());
		html.append("</span>");
		html.append("\n\t</div>");
		
		return EVAL_BODY_BUFFERED;
	}

	public int doAfterBody() throws JspException {
		html.append("\n\t<div class=\"content\" id=\"");
		html.append(getId());
		html.append("_content\">");
		html.append(getBodyContent().getString());
		html.append("\n\t</div>");
		return SKIP_BODY;
	}

	public int doEndTag() throws JspException {
//		html.append("\n\t<div class=\"shadow\"></div>");
		html.append("\n</div>");
		
		JspWriter writer = pageContext.getOut();
		try {
			writer.write(html.toString());
		} catch (IOException e) {
			throw new JspException(e.getMessage(), e);
		}
		
		return EVAL_PAGE;
	}

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAutorefreshRate() {
		return autorefreshRate;
	}

	public void setAutorefreshRate(String autorefreshRate) {
		this.autorefreshRate = autorefreshRate;
	}

	public String getContentUrl() {
		return contentUrl;
	}

	public void setContentUrl(String contentUrl) {
		this.contentUrl = contentUrl;
	}

	public String getStyle() {
		return style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

}
