#deploy.path=C:/Arquivos de programas/Apache Software Foundation/Tomcat 5.0/webapps
deploy.path=C:/Arquivos de programas/Apache Software Foundation/Tomcat 5.5/webapps
#deploy.path=D:/jBoss3.2.5/server/default/deploy
#deploy.path=D:/Arquivos de programas/jboss/jboss-4.0.4.GA/server/default/deploy
war.dir=${deploy.path}/bolao
war.file=${war.dir}.war