africa do sul=za
albania=al
alemanha=de
arabia saudita=sa
argelia=dz
argentina=ar
australia=au
austria=at
chile=cl
belgica=be
bolivia=bo
bosnia e herzegovina=ba
brasil=br
cabo verde=cv
canada=ca
catar=qa
colombia=co
coreia do sul=kr
costa do marfim=ci
croacia=hr
curacao=cw
dinamarca=dk
egito=eg
equador=ec
escocia=gb-sct
eslovaquia=sk
espanha=es
estados unidos=us
franca=fr
gana=gh
haiti=ht
holanda=nl
inglaterra=gb-eng
ira=ir
iraque=iq
irlanda do norte=gb-nir
italia=it
jamaica=jm
japao=jp
jordania=jo
kosovo=xk
macedonia do norte=mk
marrocos=ma
mexico=mx
noruega=no
nova caledonia=nc
nova zelandia=nz
pais de gales=gb-wls
panama=pa
paraguai=py
polonia=pl
portugal=pt
republica da irlanda=ie
republica democratica do congo=cd
republica tcheca=cz
romenia=ro
senegal=sn
suecia=se
suica=ch
suriname=sr
tunisia=tn
turquia=tr
ucrania=ua
uruguai=uy
uzbequistao=uz
