-- Migration: Add real-time score update fields to JOG_JOGO
ALTER TABLE JOG_JOGO ADD COLUMN JOG_EXTERNAL_ID VARCHAR(64);
ALTER TABLE JOG_JOGO ADD COLUMN JOG_LAST_CHECKED DATETIME;
ALTER TABLE JOG_JOGO ADD COLUMN JOG_SOURCE_UPDATED DATETIME;

-- Add index for API lookups
CREATE INDEX idx_jog_external_id ON JOG_JOGO(JOG_EXTERNAL_ID);
