mail.smtp.host = smtp.bc
mail.smtp.port = 25
mail.smtp.auth = false
mail.smtp.auth.user =
mail.smtp.auth.password =
mail.pop3.host = 
mail.from.address = bolaodeplaca2006@tvcipo
mail.from.name = Bolão de Placa - TV Cipó
mail.fakereply = 
mail.property.systemurl = http://w2693674:8080/bolao